//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Genres = newGenresTable("public", "genres", "")

type genresTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnInteger
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type GenresTable struct {
	genresTable

	EXCLUDED genresTable
}

// AS creates new GenresTable with assigned alias
func (a GenresTable) AS(alias string) *GenresTable {
	return newGenresTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GenresTable with assigned schema name
func (a GenresTable) FromSchema(schemaName string) *GenresTable {
	return newGenresTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GenresTable with assigned table prefix
func (a GenresTable) WithPrefix(prefix string) *GenresTable {
	return newGenresTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GenresTable with assigned table suffix
func (a GenresTable) WithSuffix(suffix string) *GenresTable {
	return newGenresTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGenresTable(schemaName, tableName, alias string) *GenresTable {
	return &GenresTable{
		genresTable: newGenresTableImpl(schemaName, tableName, alias),
		EXCLUDED:    newGenresTableImpl("", "excluded", ""),
	}
}

func newGenresTableImpl(schemaName, tableName, alias string) genresTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
	)

	return genresTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
