//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PermissionLevels = newPermissionLevelsTable("public", "permission_levels", "")

type permissionLevelsTable struct {
	postgres.Table

	// Columns
	ID   postgres.ColumnInteger
	Name postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PermissionLevelsTable struct {
	permissionLevelsTable

	EXCLUDED permissionLevelsTable
}

// AS creates new PermissionLevelsTable with assigned alias
func (a PermissionLevelsTable) AS(alias string) *PermissionLevelsTable {
	return newPermissionLevelsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new PermissionLevelsTable with assigned schema name
func (a PermissionLevelsTable) FromSchema(schemaName string) *PermissionLevelsTable {
	return newPermissionLevelsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new PermissionLevelsTable with assigned table prefix
func (a PermissionLevelsTable) WithPrefix(prefix string) *PermissionLevelsTable {
	return newPermissionLevelsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new PermissionLevelsTable with assigned table suffix
func (a PermissionLevelsTable) WithSuffix(suffix string) *PermissionLevelsTable {
	return newPermissionLevelsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newPermissionLevelsTable(schemaName, tableName, alias string) *PermissionLevelsTable {
	return &PermissionLevelsTable{
		permissionLevelsTable: newPermissionLevelsTableImpl(schemaName, tableName, alias),
		EXCLUDED:              newPermissionLevelsTableImpl("", "excluded", ""),
	}
}

func newPermissionLevelsTableImpl(schemaName, tableName, alias string) permissionLevelsTable {
	var (
		IDColumn       = postgres.IntegerColumn("id")
		NameColumn     = postgres.StringColumn("name")
		allColumns     = postgres.ColumnList{IDColumn, NameColumn}
		mutableColumns = postgres.ColumnList{NameColumn}
	)

	return permissionLevelsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:   IDColumn,
		Name: NameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
