//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

// UseSchema sets a new schema name for all generated table SQL builder types. It is recommended to invoke
// this method only once at the beginning of the program.
func UseSchema(schema string) {
	Genres = Genres.FromSchema(schema)
	GenresTitles = GenresTitles.FromSchema(schema)
	GooseDbVersion = GooseDbVersion.FromSchema(schema)
	Movies = Movies.FromSchema(schema)
	PermissionLevels = PermissionLevels.FromSchema(schema)
	Permissions = Permissions.FromSchema(schema)
	Roles = Roles.FromSchema(schema)
	RolesPermissions = RolesPermissions.FromSchema(schema)
	Users = Users.FromSchema(schema)
	UsersPermissions = UsersPermissions.FromSchema(schema)
	UsersRoles = UsersRoles.FromSchema(schema)
}
