//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var TitlesStudios = newTitlesStudiosTable("public", "titles_studios", "")

type titlesStudiosTable struct {
	postgres.Table

	// Columns
	TitleID  postgres.ColumnInteger
	StudioID postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type TitlesStudiosTable struct {
	titlesStudiosTable

	EXCLUDED titlesStudiosTable
}

// AS creates new TitlesStudiosTable with assigned alias
func (a TitlesStudiosTable) AS(alias string) *TitlesStudiosTable {
	return newTitlesStudiosTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new TitlesStudiosTable with assigned schema name
func (a TitlesStudiosTable) FromSchema(schemaName string) *TitlesStudiosTable {
	return newTitlesStudiosTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new TitlesStudiosTable with assigned table prefix
func (a TitlesStudiosTable) WithPrefix(prefix string) *TitlesStudiosTable {
	return newTitlesStudiosTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new TitlesStudiosTable with assigned table suffix
func (a TitlesStudiosTable) WithSuffix(suffix string) *TitlesStudiosTable {
	return newTitlesStudiosTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newTitlesStudiosTable(schemaName, tableName, alias string) *TitlesStudiosTable {
	return &TitlesStudiosTable{
		titlesStudiosTable: newTitlesStudiosTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newTitlesStudiosTableImpl("", "excluded", ""),
	}
}

func newTitlesStudiosTableImpl(schemaName, tableName, alias string) titlesStudiosTable {
	var (
		TitleIDColumn  = postgres.IntegerColumn("title_id")
		StudioIDColumn = postgres.IntegerColumn("studio_id")
		allColumns     = postgres.ColumnList{TitleIDColumn, StudioIDColumn}
		mutableColumns = postgres.ColumnList{}
	)

	return titlesStudiosTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		TitleID:  TitleIDColumn,
		StudioID: StudioIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
