//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type TitlesStudios struct {
	TitleID  int64 `sql:"primary_key"`
	StudioID int64 `sql:"primary_key"`
}
